before_script:
  - apt-get update -qq && apt-get install -y -qq python3-dev python3-pip build-essential virtualenv
  - pip3 install --upgrade pip

build:
  script:
    - make ci
  artifacts:
    paths:
      - dist/
      - README.md
